//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetClass
    {
        public AspNetClass()
        {
            this.AspNetClass_FeeType = new HashSet<AspNetClass_FeeType>();
            this.AspNetSubjects = new HashSet<AspNetSubject>();
            this.AspNetFeeChallans = new HashSet<AspNetFeeChallan>();
            this.AspNetHomeworks = new HashSet<AspNetHomework>();
            this.AspNetStudent_Session_class = new HashSet<AspNetStudent_Session_class>();
            this.StudentRecurringFees = new HashSet<StudentRecurringFee>();
            this.AspNetStudents = new HashSet<AspNetStudent>();
        }
    
        public int Id { get; set; }
        public string ClassName { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string TeacherID { get; set; }
        public Nullable<int> SessionID { get; set; }
    
        public virtual ICollection<AspNetClass_FeeType> AspNetClass_FeeType { get; set; }
        public virtual AspNetSession AspNetSession { get; set; }
        public virtual ICollection<AspNetSubject> AspNetSubjects { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<AspNetFeeChallan> AspNetFeeChallans { get; set; }
        public virtual ICollection<AspNetHomework> AspNetHomeworks { get; set; }
        public virtual ICollection<AspNetStudent_Session_class> AspNetStudent_Session_class { get; set; }
        public virtual ICollection<StudentRecurringFee> StudentRecurringFees { get; set; }
        public virtual ICollection<AspNetStudent> AspNetStudents { get; set; }
    }
}
