//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSubject
    {
        public AspNetSubject()
        {
            this.AspNetAnnouncement_Subject = new HashSet<AspNetAnnouncement_Subject>();
            this.AspNetAssessment_Question = new HashSet<AspNetAssessment_Question>();
            this.AspNetAttendances = new HashSet<AspNetAttendance>();
            this.AspNetChapters = new HashSet<AspNetChapter>();
            this.AspNetLessonPlans = new HashSet<AspNetLessonPlan>();
            this.AspNetProjects = new HashSet<AspNetProject>();
            this.AspNetPTMAttendances = new HashSet<AspNetPTMAttendance>();
            this.AspNetStudent_Subject = new HashSet<AspNetStudent_Subject>();
            this.AspNetStudent_Term_Assessment = new HashSet<AspNetStudent_Term_Assessment>();
            this.AspNetStudentPerformanceReports = new HashSet<AspNetStudentPerformanceReport>();
            this.AspNetSubject_Catalog = new HashSet<AspNetSubject_Catalog>();
            this.AspNetSubject_Homework = new HashSet<AspNetSubject_Homework>();
        }
    
        public int Id { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string TeacherID { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<AspNetAnnouncement_Subject> AspNetAnnouncement_Subject { get; set; }
        public virtual ICollection<AspNetAssessment_Question> AspNetAssessment_Question { get; set; }
        public virtual ICollection<AspNetAttendance> AspNetAttendances { get; set; }
        public virtual ICollection<AspNetChapter> AspNetChapters { get; set; }
        public virtual AspNetClass AspNetClass { get; set; }
        public virtual ICollection<AspNetLessonPlan> AspNetLessonPlans { get; set; }
        public virtual ICollection<AspNetProject> AspNetProjects { get; set; }
        public virtual ICollection<AspNetPTMAttendance> AspNetPTMAttendances { get; set; }
        public virtual ICollection<AspNetStudent_Subject> AspNetStudent_Subject { get; set; }
        public virtual ICollection<AspNetStudent_Term_Assessment> AspNetStudent_Term_Assessment { get; set; }
        public virtual ICollection<AspNetStudentPerformanceReport> AspNetStudentPerformanceReports { get; set; }
        public virtual ICollection<AspNetSubject_Catalog> AspNetSubject_Catalog { get; set; }
        public virtual ICollection<AspNetSubject_Homework> AspNetSubject_Homework { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
