//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSalary
    {
        public AspNetSalary()
        {
            this.AspNetSalaryDetails = new HashSet<AspNetSalaryDetail>();
        }
    
        public int Id { get; set; }
        public string Month { get; set; }
        public string Title { get; set; }
        public Nullable<int> VirtualRoleID { get; set; }
        public string Year { get; set; }
        public Nullable<int> SessionID { get; set; }
    
        public virtual AspNetSession AspNetSession { get; set; }
        public virtual AspNetVirtualRole AspNetVirtualRole { get; set; }
        public virtual ICollection<AspNetSalaryDetail> AspNetSalaryDetails { get; set; }
    }
}
