//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetProject
    {
        public AspNetProject()
        {
            this.AspNetStudent_Project = new HashSet<AspNetStudent_Project>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string FileName { get; set; }
        public bool AcceptSubmission { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual AspNetSubject AspNetSubject { get; set; }
        public virtual ICollection<AspNetStudent_Project> AspNetStudent_Project { get; set; }
    }
}
