//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetCatalog
    {
        public AspNetCatalog()
        {
            this.AspNetSubject_Catalog = new HashSet<AspNetSubject_Catalog>();
        }
    
        public int Id { get; set; }
        public string CatalogName { get; set; }
    
        public virtual ICollection<AspNetSubject_Catalog> AspNetSubject_Catalog { get; set; }
    }
}
