//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetLessonPlanBreakdownHeading
    {
        public AspNetLessonPlanBreakdownHeading()
        {
            this.AspNetLessonPlanBreakdowns = new HashSet<AspNetLessonPlanBreakdown>();
        }
    
        public int Id { get; set; }
        public string BreakDownHeadingName { get; set; }
    
        public virtual ICollection<AspNetLessonPlanBreakdown> AspNetLessonPlanBreakdowns { get; set; }
    }
}
