//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerGroup
    {
        public LedgerGroup()
        {
            this.Ledgers = new HashSet<Ledger>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LedgerHeadID { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<Ledger> Ledgers { get; set; }
        public virtual LedgerHead LedgerHead { get; set; }
    }
}
